---

- name: install apache web server
  apt:
    name: apache2
    state: present
  delegate_to: "{{groups['vm_proxy'] | first}}"

- name: start apache webserver
  service:
    name: apache2
    state: started
    enabled: true
  delegate_to: "{{groups['vm_proxy'] | first}}"

- copy:
    content: "Hello !"
    dest: /var/www/html/index.html
  delegate_to: "{{groups['vm_proxy'] | first}}"
  