---

- name: Install haproxy
  package:
    name: haproxy
    state: present

- name: Configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: "/etc/haproxy/haproxy.cfg"
  notify: Run haproxy

- name: Run haproxy
  service:
    name: haproxy
    state: started
    enabled: yes